import subprocess

mapping = {
    "చూపించు": "print", "chuppinchu": "print",
    "తీసుకో": "input", "tisuko": "input",
    "ఒకవేళ": "if", "okavela": "if",
    "ఒకవెలలేదా": "elif", "okavelaledha": "elif",
    "లేదా": "else", "ledha": "else",
    "కొసం": "for", "kosam": "for",
    "అయితే": "while", "ayithe": "while",
    "నివారణ్చు": "def", "nivarinchu": "def",
    "వర్గం": "class", "vargam": "class",
    "తిరిగి ఇవ్వు": "return", "tirigiivvu": "return",
    "అగ్గు": "break", "aggu": "break",
    "కొనసాగించు": "continue", "konasaginchu": "continue",
    "దిగుమతి": "import", "digumati": "import",
    "నుండి": "from", "nundi": "from",
    "గా": "as", "ga": "as",
    "తో": "with", "tho": "with",
    "ప్రయత్నించు": "try", "prayatninchu": "try",
    "తప్పు": "except", "tappa": "except",
    "చివరగా": "finally", "chivariga": "finally",
    "నిజం": "True", "nijam": "True",
    "అబద్ధం": "False", "abaddham": "False",
    "ఏదీ లేదు": "None", "ediledu": "None",
    "లేకపోతే": "or", "lekapothe": "or",

    "প্রিন্ট": "print", "dekhao": "print",
    "ইনপুট": "input", "inpuṭ": "input",
    "যদি": "if", "jodi": "if",
    "নতুবা": "elif", "notuba": "elif",
    "অন্যথায়": "else", "onyothay": "else",
    "জন্য": "for", "jonno": "for",
    "যখন": "while", "jokhon": "while",
    "ফাংশন": "def", "fankshan": "def",
    "শ্রেণী": "class", "shreni": "class",
    "ফিরিয়ে_দাও": "return", "phiriye_dao": "return",
    "ভাঙো": "break", "bhango": "break",
    "চালিয়ে_যাও": "continue", "chaliye_jao": "continue",
    "ইমপোর্ট": "import", "importo": "import",
    "থেকে": "from", "theke": "from",
    "হিসেবে": "as", "hisebe": "as",
    "সহ": "with", "shoho": "with",
    "চেষ্টা": "try", "cheshta": "try",
    "ব্যতিক্রম": "except", "byatikrom": "except",
    "অবশেষে": "finally", "oboshese": "finally",
    "সত্য": "True", "shotto": "True",
    "মিথ্যা": "False", "mithya": "False",
    "কিছুই_না": "None", "kichui_na": "None",
    "অথবা": "or", "othoba": "or",

    "दर्शय": "print", "darshaya": "print",
    "गृहय": "input", "grahaya": "input",
    "यदि": "if", "yadi": "if",
    "अन्यदि": "elif", "anyadi": "elif",
    "अन्यथा": "else", "anyatha": "else",
    "अर्थम्": "for", "artham": "for",
    "यावत्": "while", "yavat": "while",
    "निर्वपय": "def", "nirupaya": "def",
    "वर्ग": "class", "varga": "class",
    "निवर्तय": "return", "nivartaya": "return",
    "विच्छेद": "break", "vicched": "break",
    "प्रवर्तय": "continue", "pravartaya": "continue",
    "आयातय": "import", "aayataya": "import",
    "यस्मात्": "from", "yasmad": "from",
    "रूपेण": "as", "rupena": "as",
    "सह": "with", "saha": "with",
    "प्रयत्न": "try", "prayatna": "try",
    "विना": "except", "vina": "except",
    "अन्ततः": "finally", "antatah": "finally",
    "सत्य": "True", "satya": "True",
    "मिथ्या": "False", "mithya": "False",
    "शून्य": "None", "shunya": "None",
    "वा": "or", "va": "or",

    "दाखवा": "print", "dakhava": "print",
    "घ्या": "input", "ghya": "input",
    "जर": "if", "jar": "if",
    "अन्यजर": "elif", "anyajar": "elif",
    "अन्यथा": "else", "anyatha": "else",
    "साठी": "for", "sathi": "for",
    "जोपर्यंत": "while", "joparyant": "while",
    "परिभाषक": "def", "paribhashakara": "def",
    "वर्ग": "class", "varg": "class",
    "परतद्या": "return", "paratdya": "return",
    "थांबा": "break", "thamba": "break",
    "चालू ठेवा": "continue", "chalutheva": "continue",
    "आयात करा": "import", "aayatkara": "import",
    "पासून": "from", "pasun": "from",
    "म्हणून": "as", "mhanun": "as",
    "सोबत": "with", "sobat": "with",
    "प्रयत्न करा": "try", "prayatnakara": "try",
    "शिवाय": "except", "sivay": "except",
    "शेवटी": "finally", "shevti": "finally",
    "खरे": "True", "khare": "True",
    "खोटे": "False", "khote": "False",
    "काहीनाही": "None", "kahinahi": "None",
    "किंवा": "or", "kinva": "or",

    "ଦେଖାନ୍ତୁ": "print", "dekhantu": "print",
    "ନେଅନ୍ତୁ": "input", "neantu": "input",
    "ଜୋଡି": "if", "jodi": "if",
    "ନହିଲେଜୋଡି": "elif", "nahilejodi": "elif",
    "ନହିଲେ": "else", "nahile": "else",
    "ପାଇଁ": "for", "pain": "for",
    "ଜେପୋରି": "while", "jepori": "while",
    "ପରିଭାଷକାର": "def", "paribhasakara": "def",
    "ଶ୍ରେଣୀ": "class", "sreni": "class",
    "ଫେରିଦାନ୍ତୁ": "return", "pheridianthu": "return",
    "ଭଙ୍ଗିଦା": "break", "bhangida": "break",
    "ଜରିରଖ": "continue", "jarirakh": "continue",
    "ଆୟାତକାର": "import", "aayatkara": "import",
    "ରୁ": "from", "ru": "from",
    "ରୂପେ": "as", "rupe": "as",
    "ସହିତ": "with", "sahita": "with",
    "ଚେଷ୍ଟାକରା": "try", "chestakara": "try",
    "ଛାଡ": "except", "chhada": "except",
    "ସେସାରେ": "finally", "sesare": "finally",
    "ସତ୍ୟ": "True", "satya": "True",
    "ମିଥ୍ୟା": "False", "mithya": "False",
    "କିଛିନାହିଁ": "None", "kichhinahi": "None",
    "କିମ୍ବା": "or", "kimba": "or",

      "બતાવો": "print", "batavo": "print",
      "લાવજો": "input", "lavjo": "input",
      "જો": "if", "jodi": "if",
      "નહિતોજો": "elif", "nahilejo": "elif",
      "નહિતો": "else", "nahile": "else",
      "માટે": "for", "mate": "for",
      "જ્યાંસુધી": "while", "jyasudhi": "while",
      "પરિભાષો": "def", "paribhasho": "def",
      "વર્ગ": "class", "varg": "class",
      "પછાાપો": "return", "pachhaapo": "return",
      "તોડો": "break", "toddo": "break",
      "ચલુરાખો": "continue", "chalurakho": "continue",
      "આયાતકરો": "import", "aayatkaro": "import",
      "થી": "from", "thi": "from",
      "તરિકે": "as", "tarike": "as",
      "સાથે": "with", "sathe": "with",
      "પ્રયત્નકરો": "try", "prayatnkaro": "try",
      "સિવાય": "except", "sivay": "except",
      "અંતેમાં": "finally", "antema": "finally",
      "સાચું": "True", "sachu": "True",
      "ખોટું": "False", "khotu": "False",
      "કૈનનથી": "None", "kainnathi": "None",
      "અથવા": "or", "athava": "or",

      "ਦਿਖਾਓ": "print", "dikhao": "print",
      "ਲੇਜਾ": "input", "leja": "input",
      "ਜੇ": "if", "je": "if",
      "ਨਹੀਂਜੇ": "elif", "nahije": "elif",
      "ਨਹੀਂਤਾਂ": "else", "nahintan": "else",
      "ਲਈ": "for", "lai": "for",
      "ਜਦਤੱਕ": "while", "jadtak": "while",
      "ਪਰਿਭਾਸ਼ਾਕਰੋ": "def", "paribhashakaro": "def",
      "ਵਰਗ": "class", "varg": "class",
      "ਵਾਪਸਦਿਓ": "return", "wapisdeo": "return",
      "ਤੋੜਦਿਓ": "break", "tordeo": "break",
      "ਜਾਰੀਰੱਖੋ": "continue", "jarirakho": "continue",
      "ਆਯਾਤਕਰੋ": "import", "aayatkaro": "import",
      "ਤੋਂ": "from", "to": "from",
      "ਦੇਤੌਰਤੇ": "as", "detaurte": "as",
      "ਨਾਲ": "with", "naal": "with",
      "ਕੋਸ਼ਿਸ਼ਕਰੋ": "try", "koshishkaro": "try",
      "ਤੋਂਇਲਾਵਾ": "except", "toillawa": "except",
      "ਅਖੀਰਕਰੇ": "finally", "akhirkare": "finally",
      "ਸੱਚ": "True", "sach": "True",
      "ਝੂਠ": "False", "jhuth": "False",
      "ਕੁਝਨਹੀਂ": "None", "kuchnahi": "None",
      "ਜਾਂ": "or", "jam": "or",

    "ಮುದ್ರಿಸು": "print", "mudrisu": "print",
    "ಒಳತೆಗೆಯು": "input", "olategayu": "input",
    "ಒಂದೇ": "if", "onde": "if",
    "ಅಥವಾ_ಒಂದೇ": "elif", "athava_onde": "elif",
    "ಅಥವಾ": "else", "athava": "else",
    "ಗಾಗಿ": "for", "gaagi": "for",
    "ವರೆಗೆ": "while", "varege": "while",
    "ವಿವರಣೆ": "def", "vivarane": "def",
    "ವರ್ಗ": "class", "varga": "class",
    "ಮರಳಿ": "return", "marali": "return",
    "ಮುರಿ": "break", "muri": "break",
    "ಮುಂದುವರಿಸು": "continue", "munduvarisu": "continue",
    "ಆಮದು": "import", "aamadu": "import",
    "ಇಂದ": "from", "inda": "from",
    "ಹೆಸರಿನಲ್ಲಿ": "as", "hesarinalli": "as",
    "ಜೊತೆಗೆ": "with", "joteghe": "with",
    "ಪ್ರಯತ್ನಿಸು": "try", "prayatnisu": "try",
    "ವ್ಯತ್ಯಾಸ": "except", "vyatyaasa": "except",
    "ಕೊನೆಯಲ್ಲಿ": "finally", "koneyalli": "finally",
    "ಸತ್ಯ": "True", "satya": "True",
    "ಸುಳ್ಳು": "False", "sullu": "False",
    "ಶೂನ್ಯ": "None", "shoonya": "None",
    "ಅಥವಾ_": "or", "athava_": "or",

    "காட்டிடு": "print", "kaattidu": "print",
    "எடுத்து": "input", "eduthu": "input",
    "என்றால்": "if", "enraal": "if",
    "இல்லை_என்றால்": "elif", "illainraal": "elif",
    "இல்லை": "else", "illai": "else",
    "காக": "for", "kaga": "for",
    "போது": "while", "pothu": "while",
    "வரையிடு": "def", "varaiyidu": "def",
    "வகுப்பு": "class", "vaguppu": "class",
    "திருப்பிடு": "return", "thiruppidu": "return",
    "நிறுத்திடு": "break", "niruthidu": "break",
    "தொடரிடு": "continue", "thodaridu": "continue",
    "உள்ளிடு": "import", "ulkollu": "import",
    "இருந்து": "from", "irundhu": "from",
    "ஆக": "as", "aaga": "as",
    "உடன்": "with", "udan": "with",
    "முயற்சிடு": "try", "muyarchidu": "try",
    "தவிர": "except", "thavira": "except",
    "இறுதியில்": "finally", "iruthil": "finally",
    "உண்மை": "True", "unmai": "True",
    "பொய்": "False", "poi": "False",
    "ஒன்றுமில்லை": "None", "onrumillai": "None",
    "அல்லது": "or", "allatu": "or",

   "കാണിക്കുക":"print","kaanikku":"print",
   "എടുക്കുക":"input","eduthu":"input",
   "എങ്കിൽ":"if","enkil":"if",
   "അഥവാ എങ്കിൽ":"elif","athavaenkil":"elif",
   "അല്ലെങ്കിൽ":"else","allenkil":"else",
   "വേണ്ടി":"for","vendiy":"for",
   "കാലം":"while","kalam":"while",
   "പരിഭാഷിക്കുക":"def","paribhashikku":"def",
   "വിഭാഗം":"class","vibhagam":"class",
   "തിരിച്ച്":"return","tirichu":"return",
   "മുറിക്കുക":"break","murikku":"break",
  "തുടരുക":"continue","thudaru":"continue",
  "അകത്തു വരുത്തുക":"import","akathuvaru":"import",
  "നിന്ന്":"from","ninnum":"from",
  "ആയായി":"as","ayitu":"as",
  "കൂടെ":"with","koodi":"with",
  "ശ്രമിക്കുക":"try","sramikku":"try",
  "വിട്ട്":"except","vitte":"except",
  "അവസാനത്ത്":"finally","avasanam":"finally",
  "സത്യം":"True","satya":"True",
  "മിഥ്യ":"False","mithya":"False",
  "ഒന്നുമില്ല":"None","onnumilla":"None",
  "allengil":"or","അല്ലെങ്കില്":"or",

    "दिखाओ": "print", "dikhao": "print",
    "लेआओ": "input", "lejao": "input",
    "अगर": "if", "agar": "if",
    "वरना अगर": "elif", "warnaagar": "elif",
    "वरना": "else", "warna": "else",
    "केलिए": "for", "kelie": "for",
    "जबतक": "while", "jabtak": "while",
    "परिभाषा_करो": "def", "paribhashakaro": "def",
    "वर्ग": "class", "varg": "class",
    "लौटाओ": "return", "lautao": "return",
    "तोड़दो": "break", "toddo": "break",
    "जारी_रखो": "continue", "jaario": "continue",
    "आयात_करो": "import", "aayatkaro": "import",
    "से": "from", "se": "from",
    "के_रूप_में": "as", "saath": "as",
    "साथ": "with", "ke_saath": "with",
    "कोशिश_करो": "try", "koshishkaro": "try",
    "सिवाय": "except", "sivay": "except",
    "अंत_में": "finally", "antme": "finally",
    "सच": "True", "sach": "True",
    "झूठ": "False", "jhooth": "False",
    "कुछनहीं": "None", "kuchnahin": "None",
    "या": "or", "ya": "or",


}

def translate(code: str) -> str:

    for hyb, eng in mapping.items():
        code = code.replace(hyb, eng)
    return code

def run_hb_file(filename="test.hb"):
    with open(filename, "r", encoding="utf-8") as f:
        hybrid_code = f.read()
    python_code = translate(hybrid_code)
    with open("temp.py", "w", encoding="utf-8") as f:
        f.write(python_code)
    subprocess.run(["python3", "temp.py"])

if __name__ == "__main__":
    run_hb_file()
